# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ntG2kmQkHyzeowyAvzMA2WIJQ5zUDHpk
"""

!pip install python-telegram-bot
!pip install adafruit-io
from telegram.ext import Updater,CommandHandler,MessageHandler,Filters
from Adafruit_IO import Client,Data
import os

def turnoffthelight(update, context):
  context.bot.send_message(chat_id=update.effective_chat.id, text="Bulb turned off")
  context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://images.app.goo.gl/SLw9KoyLmVrecKYE8')
  send_value(0)
def turnonthelight(update, context):
  context.bot.send_message(chat_id=update.effective_chat.id, text="Bulb turned on")
  context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://images.app.goo.gl/CjF4N93S951ThEK49')
  send_value(1)

def send_value(value):
  feed = aio.feeds('Project')
  aio.send_data(feed.key,value)

def input_message(update, context):
  text=update.message.text
  if text == 'turnonthelight':
    send_value(1)
    context.bot.send_message(chat_id=update.effective_chat.id,text="Bulb turned on")
    context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://images.app.goo.gl/CjF4N93S951ThEK49')
    send_value(0)
    context.bot.send_message(chat_id=update.effective_chat.id,text="Bulb turned off")
    context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://images.app.goo.gl/SLw9KoyLmVrecKYE8')

def start(update,context):
  start_message='''
/turnoff the light or 'turn off':To turn off the bulb ,sends value=0 in feed
/turnon the light or 'turn on'  :To turn on the bulb ,sends value=1 in feed
'''
  context.bot.send_message(chat_id=update.effective_chat.id, text=start_message)

ADAFRUIT_IO_USERNAME =  os.getenv('URK19EC1064')
ADAFRUIT_IO_KEY = os.getenv('aio_dQfv42RK0IiLLYs8RfRLCK5LOppL')
TOKEN = os.getenv('1192265925:AAHHS_2nNbuMhfb5YrtCFrmJumWqCmIyrzQ')

aio = Client('URK19EC1064','aio_dQfv42RK0IiLLYs8RfRLCK5LOppL')
updater=Updater('1192265925:AAHHS_2nNbuMhfb5YrtCFrmJumWqCmIyrzQ',use_context=True)
dispatcher = updater.dispatcher
dispatcher.add_handler(CommandHandler('turnoffthelight',turnoffthelight))
dispatcher.add_handler(CommandHandler('turnonthelight',turnonthelight))
dispatcher.add_handler(CommandHandler('start',start))
dispatcher.add_handler(MessageHandler(Filters.text & (~Filters.command),input_message))
updater.start_polling()
updater.idle()